security:
    jwt:
        token:
            secret-key: ${TOKEN_JWT}
            expire-length: ${TOKEN_EXPIRE}
spring:
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
