server:
    port: 8080
spring:
    profiles:
        active: dev
    application:
        name: api-files
    datasource:
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.PostgreSQLDialect
spring-doc:
    pathsToMatch: /v1/api/**
    swagger-ui:
        use-root-path: true
