server:
    port: 8080
cors:
    originPatterns: http://localhost:3000
spring:
    profiles:
        active: dev
    application:
        name: api-files
    datasource:
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.PostgreSQLDialect
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
spring-doc:
    pathsToMatch: /v1/api/**
    swagger-ui:
        use-root-path: true
files:
    directory:
        uploads: uploads
        backups: backups
